### ISSUE TITLE
[22th] line 539: "압축되지 않은 커널의 크기를 압축된 데이터 끝에 추가한다"라고 하는데 실제 코드는 압축되지 않은 커널의 크기가 아니라 압축된 커널의 크기?

### ISSUE THREAD

**Issue by onkwon** [iamroot12b/kernel#11]
압축된 데이터 끝에 쓰는 건 맞습니다만, 쓰이는 값은 압축되지 않은 커널의 크기가 아닌 압축된 커널(piggy.gzip)의 크기입니다. 다만 head.o와 misc.o가 포함되어 있습니다. 원문에서 말하는 decompressed kernel이란 바로 head.o + misc.o + piggy.gzip을 말하는 걸까요? 아니면 우리가 놓치고 있는 어떤 부분이 있는 걸까요?

**Comment by hellojaewon** [comment]
어제 스터디 시간에 말씀해주셨듯이, gzip의 마지막 4바이트에 압축되지 않은 원래의 데이터 사이즈가 있었네요.
(정확하게는 x % 2^32 (where x is decompressed size)

```
           0   1   2   3   4   5   6   7
         +---+---+---+---+---+---+---+---+
         |     CRC32     |     ISIZE     |
         +---+---+---+---+---+---+---+---+

ISIZE (Input SIZE)
            This contains the size of the original (uncompressed) input
            data modulo 2^32.
```

그리고 이때 byte ordering은 little endian 방식으로 저장되어 있었습니다.
실제로 원래 파일 크기가 34,349 bytes인 파일을 gzip으로 압축해서 gunzip으로 uncompressed size 읽은 것과, 마지막 4바이트를 little endian으로 해석 한 값이 동일한 것을 확인했습니다.

``` gunzip
[/Users/jwchoi/test]gunzip -l test.cpp.gz 
  compressed uncompressed  ratio uncompressed_name
        8027        34349  76.6% test.cpp
[/Users/jwchoi/test]
```

``` hexdump
[/Users/jwchoi/test]hexdump test.cpp.gz 
0000000 1f 8b 08 08 66 c7 19 56 00 03 74 65 73 74 2e 63
0000010 70 70 00 cd 3d fd 53 1b 47 b2 bf f3 57 8c 75 15
.....
0001f40 d7 88 55 a1 8c 66 93 cb 6b 54 5b 14 30 fa 5f f0
0001f50 dd ff 01 ea 84 5c 14 2d 86 00 00               
0001f5b
[/Users/jwchoi/test]
```

마지막 4 바이트 2d 86 00 00을 little endian으로 해석해서 10진수로 변환하면 34,349 입니다.

그래서 아래 코드는 결국, piggy.gz의 압축 하기 이전의 원래 크기의 little-endian 표현을 r10에 읽었기 때문에, 이후 계산에 사용하기 위해 r9에 big-endian으로 변환해서 저장하는 코드였네요.
주석에는 kernel build system이라고 되어 있는데, 오히려 정확하게는 gzip의 spec에 대한 내용이 있었더라면 더 좋았을 것 같습니다.

```
        /*   
         * The kernel build system appends the size of the
         * decompressed kernel at the end of the compressed data
         * in little-endian form.
         */
        ldrb    r9, [r10, #0]
        ldrb    lr, [r10, #1]
        orr r9, r9, lr, lsl #8
        ldrb    lr, [r10, #2]
        ldrb    r10, [r10, #3]
        orr r9, r9, lr, lsl #16
        orr r9, r9, r10, lsl #24
```

References
https://tools.ietf.org/html/rfc1952 (gzip rfc spec)
http://www.onicos.com/staff/iz/formats/gzip.html

**Comment by onkwon** [comment]
저도 어제 집에 돌아와서 `piggy.gz`이 만들어지는 과정을 추적해봤습니다. 마지막 워드에 저장되는 사이즈가 어떤 사이즈인지 확실히하기 위해서요.

```
194 $(obj)/piggy.$(suffix_y): $(obj)/../Image FORCE
195         $(call if_changed,$(suffix_y))
196 
197 $(obj)/piggy.$(suffix_y).o:  $(obj)/piggy.$(suffix_y) FORCE
```

그런데 위 코드와 같이 `arch/arm/boot/compressed/Makefile`에서 `gzip` 이후에 파일 사이즈를 추가하는 부분을 어디에서도 찾을 수가 없었습니다. 그 이유가 재원씨가 알려주신데로 gzip의 규격이었다니!!

그럼 본 이슈는 닫도록 하겠습니다.
