### ISSUE TITLE
__setup_mmu: 페이지 디렉토리 주소를 정렬할 때 bic 명령을 두번으로 나누어서 정렬

### ISSUE THREAD

**Issue by onkwon** [iamroot12b/kernel#4]
페이지 디렉토리 주소를 정렬할 때 bic 명령을 두번으로 나누어서 정렬하는 이유?

```
bic     r3, r3, #0xff           @ Align the pointer
bic     r3, r3, #0x3f00
```

**Comment by hellojaewon** [comment]
이 것도 https://github.com/torvalds/linux의 head.S commit 이력을 봐도 따로 찾을 수가 없네요...
별 다른 의미는 없을 것 같습니다.

```
bic    r3, r3, 0x3fff
```

이렇게 해도 잘 동작할 것 같네요~

__armv7_mmu_cache_on: 레이블에도 bic를 나눠서 사용하는 코드가 있는데 이건 shift로 비트를 생성해내는 코드라...

```
__armv7_mmu_cache_on:
...
bic    r6, r6, #1 << 31
bic    r6, r6, #3 << 0
...
```

**Comment by Xeite** [comment]
http://www.cprogramdevelop.com/2189651/

이 사이트에 이유가 나와있네요. 

8-deposit data: explain "The constant must correspond eight bitmap 

constant value를 사용할때는 8비트 밖에 안되는것 같습니다.

**Comment by onkwon** [comment]
말씀하신대로인 것 같아요. 배럴 시프트를 처음 봤을 때 `와~ 아이디어 좋다`라고 생각했었는데 링크된 글 보고 한번 더 감탄했어요.

사실 처음 의심하기를 명령어내 피연산자의 필드 영역이 작아서일 거라고 생각했거든요. 그래서 어셈블러에서 시프트 연산으로 조정하는게 아닐까 추측했었는데 디스어셈블해보니까 그렇지가 않더라고요. 그런데 하드웨어적으로 이런 트릭이 숨어있었네요.

아래는 관련내용 간단 요약이에요:

ARM은 다른 RISC 프로세서들과 마찬가지로 고정된 32비트 명령어 크기를 갖는다. 이는 명령어 디코딩과 파이프라인 적용을 용이하게 하는 한편, 명령어와 함께 인코딩되는 상수immediate value값의 표현 범위를 제한한다.

데이터 연산 명령어의 25번째 비트는 operand2가 상수인지 레지스터인지 결정하는 플래그이다. operand2는 하위 12비트를 차지하는데 이는 0 ~ 4095 값만을 표현할 수 있다. 이런 제약을 돌파하기 위해 ARM은 12비트 중 상위 4비트를 로테이트 시프트 값으로, 하위 8비트를 상수값으로 사용한다.

4비트는 16가지(0~15) 경우의 수를 가지므로 8비트의 상수값을 32비트 값으로 확장하기에는 역부족이다. 하지만, 로테이트 값을 2로 곱하면 32비트 표현이(0~30, 단 짝수만) 가능해진다. 즉, 0~31까지의 2의 누승값을 표현할 수 있으므로, 하나의 명령어는 32비트 내의 어떤 비트든 조작할 수 있게된다.

참고:
http://alisdair.mcdiarmid.org/arm-immediate-value-encoding/
http://www.davespace.co.uk/arm/introduction-to-arm/immediates.html

**Comment by hellojaewon** [comment]
명확하네요~:+1: 
스터디때도 내용 공유하면 좋을 것 같습니다. 확인못하신 분들도 계실것같으니.
고맙습니다!!
